name: Test, Build, and Push to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements 
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pytest
      - name: Run tests
        env: 
          Mode: "github actions"
        run: |
          pytest src/tests.py   
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container image
        run: |
            docker build -f Dockerfile -t serverless-py . 
            
