name: Test, Build, and Push to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements 
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pytest
      - name: Run tests
        env: 
          Mode: "github actions"
        run: |
          pytest src/tests.py   
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{secrets.GOOGLE_CREDENTIAL}}'
      - name: Build container image
        run: |
            docker build -f Dockerfile -t serverless-py .    
            docker tag serverless-py ${{secrets.CONTAINER_IMAGE_URL}}:latest
            docker tag serverless-py ${{secrets.CONTAINER_IMAGE_URL}}:${GITHUB_RUN_ID}
            gcloud auth configure-docker ${{secrets.GCLOUD_REGION}}-docker.pkg.dev
            docker push ${{secrets.CONTAINER_IMAGE_URL}} --all-tags
      - name: Deploy container to cloud run 
        run: |
          gcloud run deploy serverless-py-runs \
          --image=${{secrets.CONTAINER_IMAGE_URL}}:latest \
          --allow-unauthenticated \
          --region=${{secrets.GCLOUD_REGION}} \
          --project=${{secrets.GCLOUD_PROJECT_ID}}
      